In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


In [2]:
train_data=pd.read_csv("Titanic Forecast/data/train.csv")
# test_data=train_data['Survived']
test_data=pd.read_csv("Titanic Forecast/data/test.csv")

In [3]:
datasets=[train_data,test_data]

In [4]:
datasets

[     PassengerId  Survived  Pclass  \
 0              1         0       3   
 1              2         1       1   
 2              3         1       3   
 3              4         1       1   
 4              5         0       3   
 5              6         0       3   
 6              7         0       1   
 7              8         0       3   
 8              9         1       3   
 9             10         1       2   
 10            11         1       3   
 11            12         1       1   
 12            13         0       3   
 13            14         0       3   
 14            15         0       3   
 15            16         1       2   
 16            17         0       3   
 17            18         1       2   
 18            19         0       3   
 19            20         1       3   
 20            21         0       2   
 21            22         1       2   
 22            23         1       3   
 23            24         1       1   
 24            25        

In [5]:
test_data

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [6]:
train_data.keys()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
test_data.keys()

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
clf=DecisionTreeClassifier()

In [9]:
train_data[['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [10]:
#checking traindata is equal to the total size of datas or not

In [11]:
for dataset in datasets:
    np.unique(dataset['PassengerId'].values).size,np.unique(dataset['PassengerId'].values).size == dataset.shape[0]

In [12]:
import re
regular = re.compile('\s(\S+\.)')
designation_train = np.array([re.search(regular,i)[1] for i in train_data['Name'].values])
designation_test = np.array([re.search(regular,i)[1] for i in test_data['Name'].values])


In [13]:
train_data=train_data.drop('Name',axis=1)
test_data=test_data.drop('Name',axis=1)

In [14]:
Title=pd.DataFrame({"Title":designation_train})


In [15]:
train_data = pd.concat([train_data, Title], axis=1)
Title=pd.DataFrame({"Title":designation_test})
test_data = pd.concat([test_data, Title], axis=1)

In [16]:
train_data['Title'].groupby(train_data['Title']).size()
test_data['Title'].groupby(test_data['Title']).size()

Title
Col.         2
Dona.        1
Dr.          1
Master.     21
Miss.       78
Mr.        240
Mrs.        72
Ms.          1
Rev.         2
Name: Title, dtype: int64

In [17]:
train_data['Title'] = train_data['Title'].replace('Mlle.','Miss.')
train_data['Title'] = train_data['Title'].replace('Ms.','Miss.')  
train_data['Title'] = train_data['Title'].replace('Mme.','Mrs.')
train_data['Title'] = train_data['Title'].replace(['Capt.','Col.','Major.'],'Army.')
train_data['Title'] = train_data['Title'].replace(['Countess.','Don.','Jonkheer.','Lady.','Sir.'],'Noble.')
test_data['Title'] = test_data['Title'].replace('Mlle.','Miss.')
test_data['Title'] = test_data['Title'].replace('Ms.','Miss.')  
test_data['Title'] = test_data['Title'].replace('Mme.','Mrs.')
test_data['Title'] = test_data['Title'].replace(['Capt.','Col.','Major.'],'Army.')
test_data['Title'] = test_data['Title'].replace(['Countess.','Don.','Jonkheer.','Lady.','Sir.'],'Noble.')

In [18]:
train_data['Title'].groupby(train_data['Title']).size()

Title
Army.        5
Dr.          7
Master.     40
Miss.      185
Mr.        517
Mrs.       126
Noble.       5
Rev.         6
Name: Title, dtype: int64

In [19]:
print('Number of survival:\n\n{}'.format(train_data[['Title','Survived']].groupby(train_data['Title']).mean()))


Number of survival:

         Survived
Title            
Army.    0.400000
Dr.      0.428571
Master.  0.575000
Miss.    0.702703
Mr.      0.156673
Mrs.     0.793651
Noble.   0.600000
Rev.     0.000000


In [20]:
train_data.drop('Ticket',axis=1,inplace=True)
test_data.drop('Ticket',axis=1,inplace=True)

In [21]:
train_data.head(0)


Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Cabin, Embarked, Title]
Index: []

In [22]:
test_data.head(0)

Empty DataFrame
Columns: [PassengerId, Pclass, Sex, Age, SibSp, Parch, Fare, Cabin, Embarked, Title]
Index: []

In [23]:
train_data.set_index(['PassengerId'],inplace=True)
test_data.set_index(['PassengerId'],inplace=True)

In [24]:
def modify_cabin(cabin):
    if pd.isnull(cabin):
        cat = 'None'
    else:
        cat = cabin[0]
    return cat

In [25]:
cabin_category = np.array([modify_cabin(cab) for cab in train_data['Cabin'].values])
cabin_category_test = np.array([modify_cabin(cab) for cab in test_data['Cabin'].values])

In [26]:
cabin_category

array(['None', 'C', 'None', 'C', 'None', 'None', 'E', 'None', 'None',
       'None', 'G', 'C', 'None', 'None', 'None', 'None', 'None', 'None',
       'None', 'None', 'None', 'D', 'None', 'A', 'None', 'None', 'None',
       'C', 'None', 'None', 'None', 'B', 'None', 'None', 'None', 'None',
       'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None',
       'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None',
       'D', 'None', 'B', 'C', 'None', 'None', 'None', 'None', 'None', 'B',
       'C', 'None', 'None', 'None', 'F', 'None', 'None', 'None', 'None',
       'None', 'None', 'None', 'None', 'F', 'None', 'None', 'None',
       'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None',
       'None', 'C', 'None', 'None', 'None', 'E', 'None', 'None', 'None',
       'A', 'D', 'None', 'None', 'None', 'None', 'D', 'None', 'None',
       'None', 'None', 'None', 'None', 'None', 'C', 'None', 'None',
       'None', 'None', 'None', 'None', 'None', 'B', 'None', 'None',
   

In [27]:
train_data=train_data.assign(Cabs_Category=cabin_category)
test_data=test_data.assign(Cabs_Category=cabin_category_test)


In [28]:
train_data=train_data.drop('Cabin',axis=1)
test_data=test_data.drop('Cabin',axis=1)


In [29]:
print("no. of passengers{}".format(train_data['Cabs_Category'].groupby(train_data['Cabs_Category']).size()))

no. of passengersCabs_Category
A        15
B        47
C        59
D        33
E        32
F        13
G         4
None    687
T         1
Name: Cabs_Category, dtype: int64


In [30]:
survived_data = train_data.loc[train_data['Survived']==1,:]

In [31]:
survived_data


Survived  Pclass     Sex    Age  SibSp  Parch      Fare Embarked  \
PassengerId                                                                     
2                   1       1  female  38.00      1      0   71.2833        C   
3                   1       3  female  26.00      0      0    7.9250        S   
4                   1       1  female  35.00      1      0   53.1000        S   
9                   1       3  female  27.00      0      2   11.1333        S   
10                  1       2  female  14.00      1      0   30.0708        C   
11                  1       3  female   4.00      1      1   16.7000        S   
12                  1       1  female  58.00      0      0   26.5500        S   
16                  1       2  female  55.00      0      0   16.0000        S   
18                  1       2    male    NaN      0      0   13.0000        S   
20                  1       3  female    NaN      0      0    7.2250        C   
22                  1       2    male  34.00      0      0   13.0000        S   
23                  1       3  female  15.00      0      0    8.0292        Q   
24                  1       1    male  28.00      0      0   35.5000        S   
26                  1       3  female  38.00      1      5   31.3875        S   
29                  1       3  female    NaN      0      0    7.8792        Q   
32                  1       1  female    NaN      1      0  146.5208        C   
33                  1       3  female    NaN      0      0    7.7500        Q   
37                  1       3    male    NaN      0      0    7.2292        C   
40                  1       3  female  14.00      1      0   11.2417        C   
44                  1       2  female   3.00      1      2   41.5792        C   
45                  1       3  female  19.00      0      0    7.8792        Q   
48                  1       3  female    NaN      0      0    7.7500        Q   
53                  1       1  female  49.00      1      0   76.7292        C   
54                  1       2  female  29.00      1      0   26.0000        S   
56                  1       1    male    NaN      0      0   35.5000        S   
57                  1       2  female  21.00      0      0   10.5000        S   
59                  1       2  female   5.00      1      2   27.7500        S   
62                  1       1  female  38.00      0      0   80.0000      NaN   
66                  1       3    male    NaN      1      1   15.2458        C   
67                  1       2  female  29.00      0      0   10.5000        S   
...               ...     ...     ...    ...    ...    ...       ...      ...   
810                 1       1  female  33.00      1      0   53.1000        S   
821                 1       1  female  52.00      1      1   93.5000        S   
822                 1       3    male  27.00      0      0    8.6625        S   
824                 1       3  female  27.00      0      1   12.4750        S   
828                 1       2    male   1.00      0      2   37.0042        C   
829                 1       3    male    NaN      0      0    7.7500        Q   
830                 1       1  female  62.00      0      0   80.0000      NaN   
831                 1       3  female  15.00      1      0   14.4542        C   
832                 1       2    male   0.83      1      1   18.7500        S   
836                 1       1  female  39.00      1      1   83.1583        C   
839                 1       3    male  32.00      0      0   56.4958        S   
840                 1       1    male    NaN      0      0   29.7000        C   
843                 1       1  female  30.00      0      0   31.0000        C   
850                 1       1  female    NaN      1      0   89.1042        C   
854                 1       1  female  16.00      0      1   39.4000        S   
856                 1       3  female  18.00      0      1    9.3500        S   
857                 1       1  female  45.00

In [32]:
died_data=train_data.loc[train_data['Survived']==0,:]

In [33]:
died_data

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked  \
PassengerId                                                                    
1                   0       3    male  22.0      1      0    7.2500        S   
5                   0       3    male  35.0      0      0    8.0500        S   
6                   0       3    male   NaN      0      0    8.4583        Q   
7                   0       1    male  54.0      0      0   51.8625        S   
8                   0       3    male   2.0      3      1   21.0750        S   
13                  0       3    male  20.0      0      0    8.0500        S   
14                  0       3    male  39.0      1      5   31.2750        S   
15                  0       3  female  14.0      0      0    7.8542        S   
17                  0       3    male   2.0      4      1   29.1250        Q   
19                  0       3  female  31.0      1      0   18.0000        S   
21                  0       2    male  35.0      0      0   26.0000        S   
25                  0       3  female   8.0      3      1   21.0750        S   
27                  0       3    male   NaN      0      0    7.2250        C   
28                  0       1    male  19.0      3      2  263.0000        S   
30                  0       3    male   NaN      0      0    7.8958        S   
31                  0       1    male  40.0      0      0   27.7208        C   
34                  0       2    male  66.0      0      0   10.5000        S   
35                  0       1    male  28.0      1      0   82.1708        C   
36                  0       1    male  42.0      1      0   52.0000        S   
38                  0       3    male  21.0      0      0    8.0500        S   
39                  0       3  female  18.0      2      0   18.0000        S   
41                  0       3  female  40.0      1      0    9.4750        S   
42                  0       2  female  27.0      1      0   21.0000        S   
43                  0       3    male   NaN      0      0    7.8958        C   
46                  0       3    male   NaN      0      0    8.0500        S   
47                  0       3    male   NaN      1      0   15.5000        Q   
49                  0       3    male   NaN      2      0   21.6792        C   
50                  0       3  female  18.0      1      0   17.8000        S   
51                  0       3    male   7.0      4      1   39.6875        S   
52                  0       3    male  21.0      0      0    7.8000        S   
...               ...     ...     ...   ...    ...    ...       ...      ...   
845                 0       3    male  17.0      0      0    8.6625        S   
846                 0       3    male  42.0      0      0    7.5500        S   
847                 0       3    male   NaN      8      2   69.5500        S   
848                 0       3    male  35.0      0      0    7.8958        C   
849                 0       2    male  28.0      0      1   33.0000        S   
851                 0       3    male   4.0      4      2   31.2750        S   
852                 0       3    male  74.0      0      0    7.7750        S   
853                 0       3  female   9.0      1      1   15.2458        C   
855                 0       2  female  44.0      1      0   26.0000        S   
860                 0       3    male   NaN      0      0    7.2292        C   
861                 0       3    male  41.0      2      0   14.1083        S   
862                 0       2    male  21.0      1      0   11.5000        S   
864                 0       3  female   NaN      8      2   69.5500        S   
865                 0       2    male  24.0      0      0   13.0000        S   
868                 0       1    male  31.0      0      0   50.4958        S   
869                 0       3    male   NaN      0      0    9.5000        S   
871                 0       3    male  26.0      0      0    7.8958        S   
873          

In [34]:
survived_data.keys()

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Title', 'Cabs_Category'],
      dtype='object')

In [35]:
survived_male_data=survived_data.loc[survived_data['Sex']=='male']

In [36]:
died_male_data=died_data.loc[died_data['Sex']=='male']

In [37]:
survived_female_data=survived_data.loc[survived_data['Sex']=='female']

In [38]:
died_female_data=died_data.loc[died_data['Sex']=='female']

In [39]:
survived_male_data.groupby(survived_male_data['Sex']).size()

Sex
male    109
dtype: int64

In [40]:
survived_female_data.groupby(survived_female_data['Sex']).size()

Sex
female    233
dtype: int64

In [41]:
died_male_data.groupby(died_male_data['Sex']).size()

Sex
male    468
dtype: int64

In [42]:
died_female_data.groupby(died_female_data['Sex']).size()

Sex
female    81
dtype: int64

In [43]:
train_data["Age"].fillna(train_data.groupby("Title")["Age"].transform("median"), inplace=True)
test_data["Age"].fillna(test_data.groupby("Title")["Age"].transform("median"), inplace=True)

In [44]:
train_data[[ 'Age']].info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 1 columns):
Age    891 non-null float64
dtypes: float64(1)
memory usage: 53.9 KB


In [45]:
test_data[[ 'Age']].info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 1 columns):
Age    418 non-null float64
dtypes: float64(1)
memory usage: 6.5 KB


In [46]:
train_data["Age"].fillna(train_data.groupby("Title")["Age"].transform("median"), inplace=True)

In [47]:
test_data["Age"].fillna(test_data.groupby("Title")["Age"].transform("median"), inplace=True)

In [48]:
train_data.head(0)

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked, Title, Cabs_Category]
Index: []

In [49]:
test_data.head(0)

Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked, Title, Cabs_Category]
Index: []

In [50]:
train_data[['Sex','Embarked','Title','Cabs_Category']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 4 columns):
Sex              891 non-null object
Embarked         889 non-null object
Title            891 non-null object
Cabs_Category    891 non-null object
dtypes: object(4)
memory usage: 74.8+ KB


In [51]:
print('Average survival:\n{}'.format(train_data[['Embarked',
    'Survived']].groupby('Embarked').mean()))
print('\n')
print('{}'.format(train_data[['Cabs_Category',
    'Survived']].groupby('Cabs_Category').mean()))
print('\n')
print('{}'.format(train_data[['Title',
    'Survived']].groupby('Title').mean()))



Average survival:
          Survived
Embarked          
C         0.553571
Q         0.389610
S         0.336957


               Survived
Cabs_Category          
A              0.466667
B              0.744681
C              0.593220
D              0.757576
E              0.750000
F              0.615385
G              0.500000
None           0.299854
T              0.000000


         Survived
Title            
Army.    0.400000
Dr.      0.428571
Master.  0.575000
Miss.    0.702703
Mr.      0.156673
Mrs.     0.793651
Noble.   0.600000
Rev.     0.000000


In [52]:
train_data.loc[pd.isnull(train_data['Embarked'])]

Survived  Pclass     Sex   Age  SibSp  Parch  Fare Embarked  \
PassengerId                                                                
62                  1       1  female  38.0      0      0  80.0      NaN   
830                 1       1  female  62.0      0      0  80.0      NaN   

             Title Cabs_Category  
PassengerId                       
62           Miss.             B  
830           Mrs.             B

In [53]:
test_data.loc[pd.isnull(test_data['Embarked'])]

Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked, Title, Cabs_Category]
Index: []

In [54]:
from sklearn.preprocessing import LabelEncoder
label_sex = LabelEncoder()
sex_numerical = label_sex.fit_transform(train_data['Sex'])
sex_numerical_classes = label_sex.classes_

label_sex_test = LabelEncoder()
sex_test_numerical = label_sex_test.fit_transform(test_data['Sex'])
sex_test_numerical_classes = label_sex_test.classes_
print('Classes of Sex feature:\n{}\n{}'.format(np.arange(len(sex_numerical_classes)),sex_numerical_classes))

Classes of Sex feature:
[0 1]
['female' 'male']


In [55]:
label_title = LabelEncoder()
title_numerical = label_title.fit_transform(train_data['Title'])
title_numerical_classes = label_title.classes_

label_title_test = LabelEncoder()
title_test_numerical = label_title_test.fit_transform(test_data['Title'])
title_test_numerical_classes = label_title_test.classes_
print('Classes of title feature:\n{}\n{}'.format(np.arange(len(title_numerical_classes)),title_numerical_classes))

Classes of title feature:
[0 1 2 3 4 5 6 7]
['Army.' 'Dr.' 'Master.' 'Miss.' 'Mr.' 'Mrs.' 'Noble.' 'Rev.']


In [56]:
label_Cabin = LabelEncoder()
Cabin_numerical = label_Cabin.fit_transform(train_data['Cabs_Category'])
Cabin_numerical_classes = label_Cabin.classes_

label_Cabin_test = LabelEncoder()
Cabin_test_numerical = label_Cabin_test.fit_transform(test_data['Cabs_Category'])
Cabin_test_numerical_classes = label_Cabin_test.classes_
print('Classes of title feature:\n{}\n{}'.format(np.arange(len(Cabin_numerical_classes)),Cabin_numerical_classes))

Classes of title feature:
[0 1 2 3 4 5 6 7 8]
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'None' 'T']


In [57]:
from sklearn.preprocessing import OneHotEncoder

In [58]:
encoder_Sex=OneHotEncoder(sparse=False)#will return array
sex_onehot = encoder_Sex.fit_transform(sex_numerical.reshape(-1,1))

encoder_Sex_test=OneHotEncoder(sparse=False)#will return array
sex_test_onehot = encoder_Sex_test.fit_transform(sex_test_numerical.reshape(-1,1))
print(sex_onehot)

print(sex_onehot.shape)

[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]
(891, 2)


In [59]:
encoder_Title=OneHotEncoder(sparse=False)#will return array
Title_onehot = encoder_Title.fit_transform(title_numerical.reshape(-1,1))
encoder_Title_test=OneHotEncoder(sparse=False)#will return array
Title_test_onehot = encoder_Title_test.fit_transform(title_test_numerical.reshape(-1,1))
print(Title_onehot)
print(Title_onehot.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(891, 8)


In [60]:
encoder_Cabin=OneHotEncoder(sparse=False)
Cabin_onehot=encoder_Cabin.fit_transform(Cabin_numerical.reshape(-1,1))

encoder_Cabin_test=OneHotEncoder(sparse=False)
Cabin_test_onehot=encoder_Cabin_test.fit_transform(Cabin_test_numerical.reshape(-1,1))
print(Cabin_onehot)
print(Cabin_onehot.shape)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
(891, 9)


In [61]:
def oneHotLabels(train_data,column,onehot_labeled,class_labels):
    new_assigns={}
    for c_id,label in enumerate(class_labels):
        new_assigns[column+'_'+label]=onehot_labeled[:,c_id]
    train_data=train_data.assign(**new_assigns)
    return train_data

In [62]:
test_data.head(5)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked Title  \
PassengerId                                                               
892               3    male  34.5      0      0   7.8292        Q   Mr.   
893               3  female  47.0      1      0   7.0000        S  Mrs.   
894               2    male  62.0      0      0   9.6875        Q   Mr.   
895               3    male  27.0      0      0   8.6625        S   Mr.   
896               3  female  22.0      1      1  12.2875        S  Mrs.   

            Cabs_Category  
PassengerId                
892                  None  
893                  None  
894                  None  
895                  None  
896                  None

In [63]:
train_data=oneHotLabels(train_data,'Sex',sex_onehot,sex_numerical_classes)
train_data=train_data.drop('Sex',axis=1)

test_data=oneHotLabels(test_data,'Sex',sex_test_onehot,sex_test_numerical_classes)
test_data=test_data.drop('Sex',axis=1)

In [64]:
train_data=oneHotLabels(train_data,'Title',Title_onehot,title_numerical_classes)
train_data=train_data.drop('Title',axis=1)

test_data=oneHotLabels(test_data,'Title',Title_test_onehot,title_test_numerical_classes)
test_data=test_data.drop('Title',axis=1)

In [65]:
train_data=oneHotLabels(train_data,'Cabs_Category',Cabin_onehot,Cabin_numerical_classes)
train_data=train_data.drop('Cabs_Category',axis=1)

test_data=oneHotLabels(test_data,'Cabs_Category',Cabin_test_onehot,Cabin_test_numerical_classes)
test_data=test_data.drop('Cabs_Category',axis=1)

In [66]:
train_data.head(0)

Empty DataFrame
Columns: [Survived, Pclass, Age, SibSp, Parch, Fare, Embarked, Sex_female, Sex_male, Title_Army., Title_Dr., Title_Master., Title_Miss., Title_Mr., Title_Mrs., Title_Noble., Title_Rev., Cabs_Category_A, Cabs_Category_B, Cabs_Category_C, Cabs_Category_D, Cabs_Category_E, Cabs_Category_F, Cabs_Category_G, Cabs_Category_None, Cabs_Category_T]
Index: []

[0 rows x 26 columns]

In [67]:
train_data['Fare'] = train_data['Fare'].fillna(train_data['Fare'].median())
test_data['Fare'] = test_data['Fare'].fillna(test_data['Fare'].median())

In [68]:
train_data[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked',
       'Sex_female', 'Sex_male', 'Title_Army.', 'Title_Dr.', 'Title_Master.',
       'Title_Miss.', 'Title_Mr.', 'Title_Mrs.', 'Title_Noble.', 'Title_Rev.',
       'Cabs_Category_A', 'Cabs_Category_B', 'Cabs_Category_C',
       'Cabs_Category_D', 'Cabs_Category_E', 'Cabs_Category_F',
       'Cabs_Category_G', 'Cabs_Category_None', 'Cabs_Category_T']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 26 columns):
Survived              891 non-null int64
Pclass                891 non-null int64
Age                   891 non-null float64
SibSp                 891 non-null int64
Parch                 891 non-null int64
Fare                  891 non-null float64
Embarked              889 non-null object
Sex_female            891 non-null float64
Sex_male              891 non-null float64
Title_Army.           891 non-null float64
Title_Dr.             891 non-null float64
Title_Master.         891 non-null float64
Title_Miss.           891 non-null float64
Title_Mr.             891 non-null float64
Title_Mrs.            891 non-null float64
Title_Noble.          891 non-null float64
Title_Rev.            891 non-null float64
Cabs_Category_A       891 non-null float64
Cabs_Category_B       891 non-null float64
Cabs_Category_C       891 non-null float64
Cabs_Category_D       891 non-null float64
C

In [69]:
train_data['Embarked'].value_counts().max()

644

In [70]:
train_data['Embarked'].value_counts().idxmax()

'S'

In [71]:
train_data['Embarked'] = train_data['Embarked'].fillna(train_data['Embarked'].value_counts().idxmax())
test_data['Embarked'] = test_data['Embarked'].fillna(test_data['Embarked'].value_counts().idxmax())

In [72]:
train_data['Embarked']=train_data['Embarked'].map({'S':0,'C':1,'Q':2}).astype(int)
test_data['Embarked']=test_data['Embarked'].map({'S':0,'C':1,'Q':2}).astype(int)

In [73]:
train_data.loc[train_data['Fare']<=7.91,'Fare']=0
train_data.loc[(train_data['Fare'] > 7.91) & (train_data['Fare'] <= 14.454), 'Fare'] = 1
train_data.loc[(train_data['Fare'] > 14.454) & (train_data['Fare'] <= 31), 'Fare']   = 2
train_data.loc[ train_data['Fare'] > 31, 'Fare'] = 3
train_data['Fare'] = train_data['Fare'].astype(int)
    
test_data.loc[test_data['Fare']<=7.91,'Fare']=0
test_data.loc[(test_data['Fare'] > 7.91) & (test_data['Fare'] <= 14.454), 'Fare'] = 1
test_data.loc[(test_data['Fare'] > 14.454) & (test_data['Fare'] <= 31), 'Fare']   = 2
test_data.loc[ test_data['Fare'] > 31, 'Fare'] = 3
test_data['Fare'] = test_data['Fare'].astype(int)
    

In [74]:
train_data.loc[ train_data['Age'] <= 16, 'Age'] 					       = 0
train_data.loc[(train_data['Age'] > 16) & (train_data['Age'] <= 32), 'Age'] = 1
train_data.loc[(train_data['Age'] > 32) & (train_data['Age'] <= 48), 'Age'] = 2
train_data.loc[(train_data['Age'] > 48) & (train_data['Age'] <= 64), 'Age'] = 3
train_data.loc[ train_data['Age'] > 64, 'Age'] =4;

test_data.loc[ test_data['Age'] <= 16, 'Age'] 					       = 0
test_data.loc[(test_data['Age'] > 16) & (test_data['Age'] <= 32), 'Age'] = 1
test_data.loc[(test_data['Age'] > 32) & (test_data['Age'] <= 48), 'Age'] = 2
test_data.loc[(test_data['Age'] > 48) & (test_data['Age'] <= 64), 'Age'] = 3
test_data.loc[ test_data['Age'] > 64, 'Age'] =4;

In [75]:
train_data.head(5)

Survived  Pclass  Age  SibSp  Parch  Fare  Embarked  Sex_female  \
PassengerId                                                                    
1                   0       3  1.0      1      0     0         0         0.0   
2                   1       1  2.0      1      0     3         1         1.0   
3                   1       3  1.0      0      0     1         0         1.0   
4                   1       1  2.0      1      0     3         0         1.0   
5                   0       3  2.0      0      0     1         0         0.0   

             Sex_male  Title_Army.       ...         Title_Rev.  \
PassengerId                              ...                      
1                 1.0          0.0       ...                0.0   
2                 0.0          0.0       ...                0.0   
3                 0.0          0.0       ...                0.0   
4                 0.0          0.0       ...                0.0   
5                 1.0          0.0       ...                0.0   

             Cabs_Category_A  Cabs_Category_B  Cabs_Category_C  \
PassengerId                                                      
1                        0.0              0.0              0.0   
2                        0.0              0.0              1.0   
3                        0.0              0.0              0.0   
4                        0.0              0.0              1.0   
5                        0.0              0.0              0.0   

             Cabs_Category_D  Cabs_Category_E  Cabs_Category_F  \
PassengerId                                                      
1                        0.0              0.0              0.0   
2                        0.0              0.0              0.0   
3                        0.0              0.0              0.0   
4                        0.0              0.0              0.0   
5                        0.0              0.0              0.0   

             Cabs_Category_G  Cabs_Category_None  Cabs_Category_T  
PassengerId                                                        
1                        0.0                 1.0              0.0  
2                        0.0                 0.0              0.0  
3                        0.0                 1.0              0.0  
4                        0.0                 0.0              0.0  
5                        0.0                 1.0              0.0  

[5 rows x 26 columns]

In [76]:
train_data['FamilySize'] = train_data['SibSp'] + train_data['Parch'] + 1
# Create new feature IsAlone from FamilySize
train_data['IsAlone'] = 0
train_data.loc[train_data['FamilySize'] == 1, 'IsAlone'] = 1

test_data['FamilySize'] = test_data['SibSp'] + test_data['Parch'] + 1
# Create new feature IsAlone from FamilySize
test_data['IsAlone'] = 0
test_data.loc[test_data['FamilySize'] == 1, 'IsAlone'] = 1

In [77]:
train_data=train_data.drop(['SibSp'],axis=1)
test_data=test_data.drop(['SibSp'],axis=1)

In [78]:
train_data=train_data.drop(['Parch'],axis=1)
test_data=test_data.drop(['Parch'],axis=1)

In [79]:
train_data.head(5)

Survived  Pclass  Age  Fare  Embarked  Sex_female  Sex_male  \
PassengerId                                                                
1                   0       3  1.0     0         0         0.0       1.0   
2                   1       1  2.0     3         1         1.0       0.0   
3                   1       3  1.0     1         0         1.0       0.0   
4                   1       1  2.0     3         0         1.0       0.0   
5                   0       3  2.0     1         0         0.0       1.0   

             Title_Army.  Title_Dr.  Title_Master.   ...     Cabs_Category_B  \
PassengerId                                          ...                       
1                    0.0        0.0            0.0   ...                 0.0   
2                    0.0        0.0            0.0   ...                 0.0   
3                    0.0        0.0            0.0   ...                 0.0   
4                    0.0        0.0            0.0   ...                 0.0   
5                    0.0        0.0            0.0   ...                 0.0   

             Cabs_Category_C  Cabs_Category_D  Cabs_Category_E  \
PassengerId                                                      
1                        0.0              0.0              0.0   
2                        1.0              0.0              0.0   
3                        0.0              0.0              0.0   
4                        1.0              0.0              0.0   
5                        0.0              0.0              0.0   

             Cabs_Category_F  Cabs_Category_G  Cabs_Category_None  \
PassengerId                                                         
1                        0.0              0.0                 1.0   
2                        0.0              0.0                 0.0   
3                        0.0              0.0                 1.0   
4                        0.0              0.0                 0.0   
5                        0.0              0.0                 1.0   

             Cabs_Category_T  FamilySize  IsAlone  
PassengerId                                        
1                        0.0           2        0  
2                        0.0           2        0  
3                        0.0           1        1  
4                        0.0           2        0  
5                        0.0           1        1  

[5 rows x 26 columns]

In [80]:
#mean=survival rate
#count=observation
#sum=survived

In [81]:
train_data[['Age','Survived']].groupby(['Age']).agg(['mean','count','sum'])

Survived           
         mean count  sum
Age                     
0.0  0.548077   104   57
1.0  0.327345   501  164
2.0  0.436893   206   90
3.0  0.434783    69   30
4.0  0.090909    11    1

In [82]:
train_data[['Fare','Survived']].groupby(['Fare']).agg(['mean','count','sum'])

Survived           
          mean count  sum
Fare                     
0     0.197309   223   44
1     0.308756   217   67
2     0.445415   229  102
3     0.581081   222  129

In [83]:
train_data[['Embarked','Survived']].groupby(['Embarked']).agg(['mean','count','sum'])

Survived           
              mean count  sum
Embarked                     
0         0.339009   646  219
1         0.553571   168   93
2         0.389610    77   30

In [84]:
train_data[['Pclass','Survived']].groupby(['Pclass']).agg(['mean','count','sum'])

Survived           
            mean count  sum
Pclass                     
1       0.629630   216  136
2       0.472826   184   87
3       0.242363   491  119

In [85]:
train_data.keys()

Index(['Survived', 'Pclass', 'Age', 'Fare', 'Embarked', 'Sex_female',
       'Sex_male', 'Title_Army.', 'Title_Dr.', 'Title_Master.', 'Title_Miss.',
       'Title_Mr.', 'Title_Mrs.', 'Title_Noble.', 'Title_Rev.',
       'Cabs_Category_A', 'Cabs_Category_B', 'Cabs_Category_C',
       'Cabs_Category_D', 'Cabs_Category_E', 'Cabs_Category_F',
       'Cabs_Category_G', 'Cabs_Category_None', 'Cabs_Category_T',
       'FamilySize', 'IsAlone'],
      dtype='object')

In [86]:
train_data[['IsAlone','Survived']].groupby(['IsAlone']).agg(['mean','count','sum'])

Survived           
             mean count  sum
IsAlone                     
0        0.505650   354  179
1        0.303538   537  163

In [87]:
label_Age = LabelEncoder()
Age_numerical = label_Age.fit_transform(train_data['Age'])
Age_numerical_classes = label_Age.classes_

label_Age_test = LabelEncoder()
Age_test_numerical = label_Age_test.fit_transform(test_data['Age'])
Age_test_numerical_classes = label_Age_test.classes_
print('Classes of title feature:\n{}\n{}'.format(np.arange(len(Age_numerical_classes)),Age_numerical_classes))

Classes of title feature:
[0 1 2 3 4]
[0. 1. 2. 3. 4.]


In [88]:
label_Fare = LabelEncoder()
Fare_numerical = label_Fare.fit_transform(train_data['Fare'])
Fare_numerical_classes = label_Fare.classes_

label_Fare_test = LabelEncoder()
Fare_test_numerical = label_Fare_test.fit_transform(test_data['Fare'])
Fare_test_numerical_classes = label_Fare_test.classes_
print('Classes of title feature:\n{}\n{}'.format(np.arange(len(Fare_numerical_classes)),Fare_numerical_classes))

Classes of title feature:
[0 1 2 3]
[0 1 2 3]


In [89]:
label_Embarked = LabelEncoder()
Embarked_numerical = label_Embarked.fit_transform(train_data['Embarked'])
Embarked_numerical_classes = label_Embarked.classes_

label_test_Embarked = LabelEncoder()
Embarked_test_numerical = label_test_Embarked.fit_transform(test_data['Embarked'])
Embarked_test_numerical_classes = label_test_Embarked.classes_
print('Classes of title feature:\n{}\n{}'.format(np.arange(len(Embarked_numerical_classes)),Embarked_numerical_classes))

Classes of title feature:
[0 1 2]
[0 1 2]


In [90]:
encoder_Age=OneHotEncoder(sparse=False)#will return array
Age_onehot = encoder_Age.fit_transform(Age_numerical.reshape(-1,1))

encoder_Age_test=OneHotEncoder(sparse=False)#will return array
Age_test_onehot = encoder_Age_test.fit_transform(Age_test_numerical.reshape(-1,1))
print(Age_onehot)
print(Age_onehot.shape)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
(891, 5)


In [91]:
encoder_Fare=OneHotEncoder(sparse=False)#will return array
Fare_onehot = encoder_Fare.fit_transform(Fare_numerical.reshape(-1,1))
encoder_Fare_test=OneHotEncoder(sparse=False)#will return array
Fare_test_onehot = encoder_Fare_test.fit_transform(Fare_test_numerical.reshape(-1,1))
print(Fare_onehot)
print(Fare_onehot.shape)

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
(891, 4)


In [92]:
encoder_Embarked=OneHotEncoder(sparse=False)#will return array
Embarked_onehot = encoder_Embarked.fit_transform(Embarked_numerical.reshape(-1,1))

encoder_Embarked_test=OneHotEncoder(sparse=False)#will return array
Embarked_test_onehot = encoder_Embarked_test.fit_transform(Embarked_test_numerical.reshape(-1,1))
print(Embarked_onehot)
print(Embarked_onehot.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(891, 3)


In [93]:
train_data.head(5)

Survived  Pclass  Age  Fare  Embarked  Sex_female  Sex_male  \
PassengerId                                                                
1                   0       3  1.0     0         0         0.0       1.0   
2                   1       1  2.0     3         1         1.0       0.0   
3                   1       3  1.0     1         0         1.0       0.0   
4                   1       1  2.0     3         0         1.0       0.0   
5                   0       3  2.0     1         0         0.0       1.0   

             Title_Army.  Title_Dr.  Title_Master.   ...     Cabs_Category_B  \
PassengerId                                          ...                       
1                    0.0        0.0            0.0   ...                 0.0   
2                    0.0        0.0            0.0   ...                 0.0   
3                    0.0        0.0            0.0   ...                 0.0   
4                    0.0        0.0            0.0   ...                 0.0   
5                    0.0        0.0            0.0   ...                 0.0   

             Cabs_Category_C  Cabs_Category_D  Cabs_Category_E  \
PassengerId                                                      
1                        0.0              0.0              0.0   
2                        1.0              0.0              0.0   
3                        0.0              0.0              0.0   
4                        1.0              0.0              0.0   
5                        0.0              0.0              0.0   

             Cabs_Category_F  Cabs_Category_G  Cabs_Category_None  \
PassengerId                                                         
1                        0.0              0.0                 1.0   
2                        0.0              0.0                 0.0   
3                        0.0              0.0                 1.0   
4                        0.0              0.0                 0.0   
5                        0.0              0.0                 1.0   

             Cabs_Category_T  FamilySize  IsAlone  
PassengerId                                        
1                        0.0           2        0  
2                        0.0           2        0  
3                        0.0           1        1  
4                        0.0           2        0  
5                        0.0           1        1  

[5 rows x 26 columns]

In [94]:
def oneHotLabel(train_data,column,onehot_labeled,class_labels):
    new_assigns={}
    for c_id,label in enumerate(class_labels):
        print(column)
        print(label)
        print(class_labels)
#         print(onehot_labeled[:,c_id])
        print(c_id,label)
        new_assigns[column+'_'+str(label)]=onehot_labeled[:,c_id]
    train_data=train_data.assign(**new_assigns)
    return train_data

In [95]:
train_data=oneHotLabel(train_data,'Age',Age_onehot,Age_numerical_classes)#age_onehot=1 0 0 #age_numerical_class=0 1 2
train_data=train_data.drop('Age',axis=1)



Age
0.0
[0. 1. 2. 3. 4.]
0 0.0
Age
1.0
[0. 1. 2. 3. 4.]
1 1.0
Age
2.0
[0. 1. 2. 3. 4.]
2 2.0
Age
3.0
[0. 1. 2. 3. 4.]
3 3.0
Age
4.0
[0. 1. 2. 3. 4.]
4 4.0


In [96]:
test_data=oneHotLabel(test_data,'Age',Age_test_onehot,Age_test_numerical_classes)#age_onehot=1 0 0 #age_numerical_class=0 1 2
test_data=test_data.drop('Age',axis=1)

Age
0.0
[0. 1. 2. 3. 4.]
0 0.0
Age
1.0
[0. 1. 2. 3. 4.]
1 1.0
Age
2.0
[0. 1. 2. 3. 4.]
2 2.0
Age
3.0
[0. 1. 2. 3. 4.]
3 3.0
Age
4.0
[0. 1. 2. 3. 4.]
4 4.0


In [97]:
train_data.head(0)

Empty DataFrame
Columns: [Survived, Pclass, Fare, Embarked, Sex_female, Sex_male, Title_Army., Title_Dr., Title_Master., Title_Miss., Title_Mr., Title_Mrs., Title_Noble., Title_Rev., Cabs_Category_A, Cabs_Category_B, Cabs_Category_C, Cabs_Category_D, Cabs_Category_E, Cabs_Category_F, Cabs_Category_G, Cabs_Category_None, Cabs_Category_T, FamilySize, IsAlone, Age_0.0, Age_1.0, Age_2.0, Age_3.0, Age_4.0]
Index: []

[0 rows x 30 columns]

In [98]:
test_data.head(0)

Empty DataFrame
Columns: [Pclass, Fare, Embarked, Sex_female, Sex_male, Title_Army., Title_Dona., Title_Dr., Title_Master., Title_Miss., Title_Mr., Title_Mrs., Title_Rev., Cabs_Category_A, Cabs_Category_B, Cabs_Category_C, Cabs_Category_D, Cabs_Category_E, Cabs_Category_F, Cabs_Category_G, Cabs_Category_None, FamilySize, IsAlone, Age_0.0, Age_1.0, Age_2.0, Age_3.0, Age_4.0]
Index: []

[0 rows x 28 columns]

In [99]:
train_data=oneHotLabel(train_data,'Fare',Fare_onehot,Fare_numerical_classes)#age_onehot=1 0 0 #age_numerical_class=0 1 2
train_data=train_data.drop('Fare',axis=1)

test_data=oneHotLabel(test_data,'Fare',Fare_test_onehot,Fare_test_numerical_classes)#age_onehot=1 0 0 #age_numerical_class=0 1 2
test_data=test_data.drop('Fare',axis=1)

Fare
0
[0 1 2 3]
0 0
Fare
1
[0 1 2 3]
1 1
Fare
2
[0 1 2 3]
2 2
Fare
3
[0 1 2 3]
3 3
Fare
0
[0 1 2 3]
0 0
Fare
1
[0 1 2 3]
1 1
Fare
2
[0 1 2 3]
2 2
Fare
3
[0 1 2 3]
3 3


In [100]:
train_data=oneHotLabel(train_data,'Embarked',Embarked_onehot,Embarked_numerical_classes)#age_onehot=1 0 0 #age_numerical_class=0 1 2
train_data=train_data.drop('Embarked',axis=1)

test_data=oneHotLabel(test_data,'Embarked',Embarked_test_onehot,Embarked_test_numerical_classes)#age_onehot=1 0 0 #age_numerical_class=0 1 2
test_data=test_data.drop('Embarked',axis=1)

Embarked
0
[0 1 2]
0 0
Embarked
1
[0 1 2]
1 1
Embarked
2
[0 1 2]
2 2
Embarked
0
[0 1 2]
0 0
Embarked
1
[0 1 2]
1 1
Embarked
2
[0 1 2]
2 2


In [101]:
train_data.head(5)

Survived  Pclass  Sex_female  Sex_male  Title_Army.  Title_Dr.  \
PassengerId                                                                   
1                   0       3         0.0       1.0          0.0        0.0   
2                   1       1         1.0       0.0          0.0        0.0   
3                   1       3         1.0       0.0          0.0        0.0   
4                   1       1         1.0       0.0          0.0        0.0   
5                   0       3         0.0       1.0          0.0        0.0   

             Title_Master.  Title_Miss.  Title_Mr.  Title_Mrs.     ...      \
PassengerId                                                        ...       
1                      0.0          0.0        1.0         0.0     ...       
2                      0.0          0.0        0.0         1.0     ...       
3                      0.0          1.0        0.0         0.0     ...       
4                      0.0          0.0        0.0         1.0     ...       
5                      0.0          0.0        1.0         0.0     ...       

             Age_2.0  Age_3.0  Age_4.0  Fare_0  Fare_1  Fare_2  Fare_3  \
PassengerId                                                              
1                0.0      0.0      0.0     1.0     0.0     0.0     0.0   
2                1.0      0.0      0.0     0.0     0.0     0.0     1.0   
3                0.0      0.0      0.0     0.0     1.0     0.0     0.0   
4                1.0      0.0      0.0     0.0     0.0     0.0     1.0   
5                1.0      0.0      0.0     0.0     1.0     0.0     0.0   

             Embarked_0  Embarked_1  Embarked_2  
PassengerId                                      
1                   1.0         0.0         0.0  
2                   0.0         1.0         0.0  
3                   1.0         0.0         0.0  
4                   1.0         0.0         0.0  
5                   1.0         0.0         0.0  

[5 rows x 35 columns]

In [102]:
train_data_columns=train_data.drop('Survived',axis=1)
pred_data=train_data['Survived']

In [103]:
train_data.keys()

Index(['Survived', 'Pclass', 'Sex_female', 'Sex_male', 'Title_Army.',
       'Title_Dr.', 'Title_Master.', 'Title_Miss.', 'Title_Mr.', 'Title_Mrs.',
       'Title_Noble.', 'Title_Rev.', 'Cabs_Category_A', 'Cabs_Category_B',
       'Cabs_Category_C', 'Cabs_Category_D', 'Cabs_Category_E',
       'Cabs_Category_F', 'Cabs_Category_G', 'Cabs_Category_None',
       'Cabs_Category_T', 'FamilySize', 'IsAlone', 'Age_0.0', 'Age_1.0',
       'Age_2.0', 'Age_3.0', 'Age_4.0', 'Fare_0', 'Fare_1', 'Fare_2', 'Fare_3',
       'Embarked_0', 'Embarked_1', 'Embarked_2'],
      dtype='object')

In [104]:
test_data

Pclass  Sex_female  Sex_male  Title_Army.  Title_Dona.  \
PassengerId                                                           
892               3         0.0       1.0          0.0          0.0   
893               3         1.0       0.0          0.0          0.0   
894               2         0.0       1.0          0.0          0.0   
895               3         0.0       1.0          0.0          0.0   
896               3         1.0       0.0          0.0          0.0   
897               3         0.0       1.0          0.0          0.0   
898               3         1.0       0.0          0.0          0.0   
899               2         0.0       1.0          0.0          0.0   
900               3         1.0       0.0          0.0          0.0   
901               3         0.0       1.0          0.0          0.0   
902               3         0.0       1.0          0.0          0.0   
903               1         0.0       1.0          0.0          0.0   
904               1         1.0       0.0          0.0          0.0   
905               2         0.0       1.0          0.0          0.0   
906               1         1.0       0.0          0.0          0.0   
907               2         1.0       0.0          0.0          0.0   
908               2         0.0       1.0          0.0          0.0   
909               3         0.0       1.0          0.0          0.0   
910               3         1.0       0.0          0.0          0.0   
911               3         1.0       0.0          0.0          0.0   
912               1         0.0       1.0          0.0          0.0   
913               3         0.0       1.0          0.0          0.0   
914               1         1.0       0.0          0.0          0.0   
915               1         0.0       1.0          0.0          0.0   
916               1         1.0       0.0          0.0          0.0   
917               3         0.0       1.0          0.0          0.0   
918               1         1.0       0.0          0.0          0.0   
919               3         0.0       1.0          0.0          0.0   
920               1         0.0       1.0          0.0          0.0   
921               3         0.0       1.0          0.0          0.0   
...             ...         ...       ...          ...          ...   
1280              3         0.0       1.0          0.0          0.0   
1281              3         0.0       1.0          0.0          0.0   
1282              1         0.0       1.0          0.0          0.0   
1283              1         1.0       0.0          0.0          0.0   
1284              3         0.0       1.0          0.0          0.0   
1285              2         0.0       1.0          0.0          0.0   
1286              3         0.0       1.0          0.0          0.0   
1287              1         1.0       0.0          0.0          0.0   
1288              3         0.0       1.0          0.0          0.0   
1289              1         1.0       0.0          0.0          0.0   
1290              3         0.0       1.0          0.0          0.0   
1291              3         0.0       1.0          0.0          0.0   
1292              1         1.0       0.0          0.0          0.0   
1293              2         0.0       1.0          0.0          0.0   
1294              1         1.0       0.0          0.0          0.0   
1295              1         0.0       1.0          0.0          0.0   
1296              1         0.0       1.0          0.0          0.0   
1297              2         0.0       1.0          0.0          0.0   
1298              2         0.0       1.0          0.0          0.0   
1299              1         0.0       1.0          0.0          0.0   
1300              3         1.0       0.0          0.0          0.0   
1301              3         1.0       0.0          0.0          0.0   
1302              3         1.0       0.0          0.0          0.0   
1303              1         1.0      

In [105]:
test_data.keys()

Index(['Pclass', 'Sex_female', 'Sex_male', 'Title_Army.', 'Title_Dona.',
       'Title_Dr.', 'Title_Master.', 'Title_Miss.', 'Title_Mr.', 'Title_Mrs.',
       'Title_Rev.', 'Cabs_Category_A', 'Cabs_Category_B', 'Cabs_Category_C',
       'Cabs_Category_D', 'Cabs_Category_E', 'Cabs_Category_F',
       'Cabs_Category_G', 'Cabs_Category_None', 'FamilySize', 'IsAlone',
       'Age_0.0', 'Age_1.0', 'Age_2.0', 'Age_3.0', 'Age_4.0', 'Fare_0',
       'Fare_1', 'Fare_2', 'Fare_3', 'Embarked_0', 'Embarked_1', 'Embarked_2'],
      dtype='object')

In [106]:
train_data=train_data_columns.drop(['Title_Noble.','Cabs_Category_T'],axis=1)

test_data=test_data.drop(['Title_Dona.'],axis=1)

In [107]:
train_data.head(0)

Empty DataFrame
Columns: [Pclass, Sex_female, Sex_male, Title_Army., Title_Dr., Title_Master., Title_Miss., Title_Mr., Title_Mrs., Title_Rev., Cabs_Category_A, Cabs_Category_B, Cabs_Category_C, Cabs_Category_D, Cabs_Category_E, Cabs_Category_F, Cabs_Category_G, Cabs_Category_None, FamilySize, IsAlone, Age_0.0, Age_1.0, Age_2.0, Age_3.0, Age_4.0, Fare_0, Fare_1, Fare_2, Fare_3, Embarked_0, Embarked_1, Embarked_2]
Index: []

[0 rows x 32 columns]

In [109]:

X=train_data
Y=pred_data
clf=DecisionTreeClassifier()
clf.fit(X,Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [110]:
train_data.head(5)

Pclass  Sex_female  Sex_male  Title_Army.  Title_Dr.  \
PassengerId                                                         
1                 3         0.0       1.0          0.0        0.0   
2                 1         1.0       0.0          0.0        0.0   
3                 3         1.0       0.0          0.0        0.0   
4                 1         1.0       0.0          0.0        0.0   
5                 3         0.0       1.0          0.0        0.0   

             Title_Master.  Title_Miss.  Title_Mr.  Title_Mrs.  Title_Rev.  \
PassengerId                                                                  
1                      0.0          0.0        1.0         0.0         0.0   
2                      0.0          0.0        0.0         1.0         0.0   
3                      0.0          1.0        0.0         0.0         0.0   
4                      0.0          0.0        0.0         1.0         0.0   
5                      0.0          0.0        1.0         0.0         0.0   

                ...      Age_2.0  Age_3.0  Age_4.0  Fare_0  Fare_1  Fare_2  \
PassengerId     ...                                                          
1               ...          0.0      0.0      0.0     1.0     0.0     0.0   
2               ...          1.0      0.0      0.0     0.0     0.0     0.0   
3               ...          0.0      0.0      0.0     0.0     1.0     0.0   
4               ...          1.0      0.0      0.0     0.0     0.0     0.0   
5               ...          1.0      0.0      0.0     0.0     1.0     0.0   

             Fare_3  Embarked_0  Embarked_1  Embarked_2  
PassengerId                                              
1               0.0         1.0         0.0         0.0  
2               1.0         0.0         1.0         0.0  
3               0.0         1.0         0.0         0.0  
4               1.0         1.0         0.0         0.0  
5               0.0         1.0         0.0         0.0  

[5 rows x 32 columns]

In [111]:
test_data.head(5)

Pclass  Sex_female  Sex_male  Title_Army.  Title_Dr.  \
PassengerId                                                         
892               3         0.0       1.0          0.0        0.0   
893               3         1.0       0.0          0.0        0.0   
894               2         0.0       1.0          0.0        0.0   
895               3         0.0       1.0          0.0        0.0   
896               3         1.0       0.0          0.0        0.0   

             Title_Master.  Title_Miss.  Title_Mr.  Title_Mrs.  Title_Rev.  \
PassengerId                                                                  
892                    0.0          0.0        1.0         0.0         0.0   
893                    0.0          0.0        0.0         1.0         0.0   
894                    0.0          0.0        1.0         0.0         0.0   
895                    0.0          0.0        1.0         0.0         0.0   
896                    0.0          0.0        0.0         1.0         0.0   

                ...      Age_2.0  Age_3.0  Age_4.0  Fare_0  Fare_1  Fare_2  \
PassengerId     ...                                                          
892             ...          1.0      0.0      0.0     1.0     0.0     0.0   
893             ...          1.0      0.0      0.0     1.0     0.0     0.0   
894             ...          0.0      1.0      0.0     0.0     1.0     0.0   
895             ...          0.0      0.0      0.0     0.0     1.0     0.0   
896             ...          0.0      0.0      0.0     0.0     1.0     0.0   

             Fare_3  Embarked_0  Embarked_1  Embarked_2  
PassengerId                                              
892             0.0         0.0         0.0         1.0  
893             0.0         1.0         0.0         0.0  
894             0.0         0.0         0.0         1.0  
895             0.0         1.0         0.0         0.0  
896             0.0         1.0         0.0         0.0  

[5 rows x 32 columns]

In [116]:
predictions1=clf.predict(test_data)

In [117]:
len(train_data.columns)

32

In [118]:
len(test_data.columns)

32

In [119]:
test_data.columns

Index(['Pclass', 'Sex_female', 'Sex_male', 'Title_Army.', 'Title_Dr.',
       'Title_Master.', 'Title_Miss.', 'Title_Mr.', 'Title_Mrs.', 'Title_Rev.',
       'Cabs_Category_A', 'Cabs_Category_B', 'Cabs_Category_C',
       'Cabs_Category_D', 'Cabs_Category_E', 'Cabs_Category_F',
       'Cabs_Category_G', 'Cabs_Category_None', 'FamilySize', 'IsAlone',
       'Age_0.0', 'Age_1.0', 'Age_2.0', 'Age_3.0', 'Age_4.0', 'Fare_0',
       'Fare_1', 'Fare_2', 'Fare_3', 'Embarked_0', 'Embarked_1', 'Embarked_2'],
      dtype='object')

In [120]:
train_data.columns

Index(['Pclass', 'Sex_female', 'Sex_male', 'Title_Army.', 'Title_Dr.',
       'Title_Master.', 'Title_Miss.', 'Title_Mr.', 'Title_Mrs.', 'Title_Rev.',
       'Cabs_Category_A', 'Cabs_Category_B', 'Cabs_Category_C',
       'Cabs_Category_D', 'Cabs_Category_E', 'Cabs_Category_F',
       'Cabs_Category_G', 'Cabs_Category_None', 'FamilySize', 'IsAlone',
       'Age_0.0', 'Age_1.0', 'Age_2.0', 'Age_3.0', 'Age_4.0', 'Fare_0',
       'Fare_1', 'Fare_2', 'Fare_3', 'Embarked_0', 'Embarked_1', 'Embarked_2'],
      dtype='object')

In [121]:
clf.score(X,Y)

0.9090909090909091

In [131]:
def kgl_submit_csv(df,predictions,savename="titanic.csv",save=False):#default [parameter in last]
    print("Number of predictions:",len(predictions))
    print("Number of passengers",len(df.index.values))
    kgl_df=pd.DataFrame({
        "PassengerId":df.index.values,
        "Survived":predictions
    })
    print(save)
    if save:
        kgl_df.to_csv(savename,index=False)
    return kgl_df

In [132]:
test_data.head(5)

Pclass  Sex_female  Sex_male  Title_Army.  Title_Dr.  \
PassengerId                                                         
892               3         0.0       1.0          0.0        0.0   
893               3         1.0       0.0          0.0        0.0   
894               2         0.0       1.0          0.0        0.0   
895               3         0.0       1.0          0.0        0.0   
896               3         1.0       0.0          0.0        0.0   

             Title_Master.  Title_Miss.  Title_Mr.  Title_Mrs.  Title_Rev.  \
PassengerId                                                                  
892                    0.0          0.0        1.0         0.0         0.0   
893                    0.0          0.0        0.0         1.0         0.0   
894                    0.0          0.0        1.0         0.0         0.0   
895                    0.0          0.0        1.0         0.0         0.0   
896                    0.0          0.0        0.0         1.0         0.0   

                ...      Age_2.0  Age_3.0  Age_4.0  Fare_0  Fare_1  Fare_2  \
PassengerId     ...                                                          
892             ...          1.0      0.0      0.0     1.0     0.0     0.0   
893             ...          1.0      0.0      0.0     1.0     0.0     0.0   
894             ...          0.0      1.0      0.0     0.0     1.0     0.0   
895             ...          0.0      0.0      0.0     0.0     1.0     0.0   
896             ...          0.0      0.0      0.0     0.0     1.0     0.0   

             Fare_3  Embarked_0  Embarked_1  Embarked_2  
PassengerId                                              
892             0.0         0.0         0.0         1.0  
893             0.0         1.0         0.0         0.0  
894             0.0         0.0         0.0         1.0  
895             0.0         1.0         0.0         0.0  
896             0.0         1.0         0.0         0.0  

[5 rows x 32 columns]

In [133]:
a=kgl_submit_csv(test_data,predictions1,save=True)

Number of predictions: 418
Number of passengers 418
True


In [134]:
test_data.keys()

Index(['Pclass', 'Sex_female', 'Sex_male', 'Title_Army.', 'Title_Dr.',
       'Title_Master.', 'Title_Miss.', 'Title_Mr.', 'Title_Mrs.', 'Title_Rev.',
       'Cabs_Category_A', 'Cabs_Category_B', 'Cabs_Category_C',
       'Cabs_Category_D', 'Cabs_Category_E', 'Cabs_Category_F',
       'Cabs_Category_G', 'Cabs_Category_None', 'FamilySize', 'IsAlone',
       'Age_0.0', 'Age_1.0', 'Age_2.0', 'Age_3.0', 'Age_4.0', 'Fare_0',
       'Fare_1', 'Fare_2', 'Fare_3', 'Embarked_0', 'Embarked_1', 'Embarked_2'],
      dtype='object')